### ISSUE TITLE
US 02.02.01 - Comment on QR

### ISSUE THREAD

**Issue by logan11111** [CMPUT301W23T06/BinaryBandits#21]
As a player, I want to be able to comment on QR codes.

### Acceptance Criteria
- in both own QR codes and others QR codes
- in QR info screen at bottom can input a comment and press add
- all users can see the comments
- username is displayed beside comment
- comments are saved

**Comment by alexrnguyen** [comment]
Users should only be able to comment on QR codes they have scanned
