### ISSUE TITLE
US 07.02.01 - Estimate Rank

### ISSUE THREAD

**Issue by alexrnguyen** [CMPUT301W23T06/BinaryBandits#22]
As a player, I want an estimate of my ranking for the highest scoring unique QR code.

### Acceptance Criteria
- On a user's profile, they can click the highest QR and a pop up will be displayed of their estimated ranking based on their highest scoring unique QR code
- Need to implement toggle on leaderboard page to view leaderboard by highest QR code scores instead of overall points
- A suitable algorithm is used to estimate the user's ranking

### Unknowns
- user can have no QR codes to display

**Comment by logan11111** [comment]
Alex finished this
