### ISSUE TITLE
US 02.03.01 - Browse Players QR

### ISSUE THREAD

**Issue by logan11111** [CMPUT301W23T06/BinaryBandits#30]
As a player, I want to be able to browse QR codes that other players have scanned.

### Acceptance Criteria
- once clicked on another users profile get sent to users profile page
- list of QR codes displayed much like your own profile page
- can click on QR codes and be brought to QR info page
- 'delete' button is hidden on QR info page of other user
- the rest of QR info page is identical to your own QR codes

**Comment by alexrnguyen** [comment]
This user store is mostly done, but we need to detect whether a QR code selected from another player's profile has been scanned by the current user.

Case 1: QRCode scanned by current user
   -Show QRInfoActivity without delete button

Case 2: QRCode NOT scanned by current user
   -Show less detailed version of QRInfoActivity (no comments, visual representation, points). This can be similar to the Activity shown when a marker is clicked on the Map page
