### ISSUE TITLE
US 02.04.01 - See Same Scans

### ISSUE THREAD

**Issue by logan11111** [CMPUT301W23T06/BinaryBandits#34]
As a player, I want to see that other players have scanned the same QR code.

### Acceptance Criteria
- In QR info screen display count for amount of players already scanned the QR code
- whenever another user scans the QR code update the count
- count stored in database
- if no other players have scanned, default value is 0 representing nobody else has scanned

**Comment by alexrnguyen** [comment]
Instead of showing how many players have scanned a QR code, I have implemented a list of players who have scanned a QR code which is shown when "See other players" is clicked in QRCodeInfoActivity
